"""
Пример использования GithubArchiveImporter для импорта кода из архивов QwenCoder.
"""

import os
import zipfile
import tempfile
from github_importer import GithubArchiveImporter

def create_test_archive():
    """Создает тестовый ZIP-архив с простым Python-модулем для демонстрации."""
    # Создаем временную директорию
    temp_dir = tempfile.mkdtemp()
    archive_path = os.path.join(temp_dir, "qwen_code_archive.zip")
    
    # Содержимое тестового файла (код, который мог сгенерировать QwenCoder)
    test_code = '''
def calculate_sum(a, b):
    """Функция сложения двух чисел."""
    return a + b

def greet(name):
    """Функция приветствия."""
    return f"Hello, {name}! This code was generated by QwenCoder agent."

if __name__ == "__main__":
    print(greet("Developer"))
    print(f"2 + 3 = {calculate_sum(2, 3)}")
'''
    
    # Создаем структуру архива (как в GitHub: repo-name-hash/main.py)
    inner_dir = os.path.join(temp_dir, "qwen-project-abc123")
    os.makedirs(inner_dir, exist_ok=True)
    
    test_file_path = os.path.join(inner_dir, "main.py")
    with open(test_file_path, 'w', encoding='utf-8') as f:
        f.write(test_code)
    
    # Создаем ZIP-архив
    with zipfile.ZipFile(archive_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Добавляем файл с сохранением структуры папок
        arcname = os.path.relpath(test_file_path, temp_dir)
        zipf.write(test_file_path, arcname)
    
    print(f"✓ Тестовый архив создан: {archive_path}")
    return archive_path

def main():
    print("=" * 60)
    print("ДЕМОНСТРАЦИЯ РАБОТЫ GITHUB ARCHIVE IMPORTER")
    print("=" * 60)
    
    # Шаг 1: Создание тестового архива
    print("\n[1] Создание тестового архива...")
    archive_path = create_test_archive()
    
    # Шаг 2: Инициализация импортера
    print("\n[2] Инициализация импортера...")
    importer = GithubArchiveImporter(archive_path)
    
    # Шаг 3: Импорт модуля
    print("\n[3] Загрузка и импорт модуля 'main.py'...")
    try:
        module = importer.load_and_import("main.py")
        print("✓ Модуль успешно импортирован!")
        
        # Шаг 4: Использование функций из импортированного модуля
        print("\n[4] Вызов функций из импортированного модуля:")
        print("-" * 40)
        
        result_greet = module.greet("Python Developer")
        print(f"greet() -> {result_greet}")
        
        result_sum = module.calculate_sum(10, 25)
        print(f"calculate_sum(10, 25) -> {result_sum}")
        
        print("-" * 40)
        print("\n✓ Все тесты пройдены успешно!")
        
    except Exception as e:
        print(f"\n✗ Ошибка при импорте: {e}")
        raise

if __name__ == "__main__":
    main()
